// src/data.js

export const clinics = [
  {
    id: 1,
    createdTime: "2025-01-20T18:49:43.000Z",
    name: "Marietta Dental Care",
    location: "Los Algodones",
    picture: "https://via.placeholder.com/150x100?text=Marietta+Dental",
    phone: "+52 (686) 244-0416",
    address:
      "Av. A entre calle 3ra y 4ta, Vicente Guerrero, 21970 Vicente Guerrero, B.C.",
    email: "kevin_hernandez@mariettadentalcare.com.mx",
    website: "http://www.mariettadentalcare.com.mx",
    clinicSummary:
      "Marietta Dental Care, located in Los Algodones, caters primarily to international patients seeking affordable dental solutions. The clinic offers a range of services, including dental implants, oral surgery, and restorative treatments, all delivered in a professional and patient-focused environment.",
    specialties: [
      "Endodontics",
      "Oral and Maxillofacial Surgery",
      "Prosthodontics",
    ],
    highlights: ["Affordable", "Expert Implants", "International Patients"],
    brandsOfImplants: [
      "Straumann (Switzerland)",
      "Hiossen (USA)",
      "Nobel Biocare (Switzerland)",
    ],
    responseTimes: {
      veneers: "Fast (1-4 days)",
      allOns: "Fast",
      allOnsDetail: "2 trips, 3 - 5 days respectively",
      implants: "Fast",
      implantsDetail: "2 trips, 2 - 2 days respectively",
    },
    services: {
      shuttleServiceAirport: "Yes",
      shuttleServiceAppointments: "Yes",
      accommodationSupport: "Yes",
      singleTripImplants: "No",
      allInclusiveQuote: "No",
    },
    reviews: [
      {
        author: "Erendida Trujillo",
        content:
          "In May 2022, we went to Los Algodones recommended by Hector Licerio to Marietta Dental Care, since my husband urgently needed a denture implant. From the moment I called for information and made the appointment, they were very kind. The day we arrived, Don Mario made us feel like family. The office is very clean following all the health rules. Affordable prices, excellent service.",
      },
      {
        author: "Traci Pershin",
        content:
          "We made a girl's trip for dental work. The dentists are so professional, and the tools and machines are state-of-the-art. I met so many people getting veneers. You have private drivers, hotels, and the food is amazing. Extremely safe. No more USA dental for me.",
      },
      {
        author: "Carolina L. Rojo",
        content:
          "We cannot be happier. From the staff at reception to patient care, they were careful and focused on quality and detail. I will recommend to family and friends, no doubt. Thank you everyone at Marietta Dental Care!",
      },
      {
        author: "Emmalee Fernandez",
        content:
          "I recently visited Marietta Dental Care in TJ, Mexico, and received top-notch dental care, including a cleaning, 18 zirconia crowns, and 2 root canals. Dr. Fernanda was incredible—her expertise and gentle approach made the procedures comfortable. The hotel they placed us at was an amazing stay and only a block away! I highly recommend this clinic.",
      },
    ],
    procedurePricing: {
      "all-on-four": 7500,
      "all-on-six": 9500,
      "three-unit-bridge": 600,
      "bone-graft-large": 300,
      "composite-filling": 70,
      "zirconium-crown": 450,
      "snap-on-4": 5000,
      "titanium-implant": 900,
      "porcelain-veneer": 400,
      "sinus-lift": 700,
      "root-canal": 300,
      "temporary-crown": 30,
      "iv-sedation": 600,
      "dental-cleaning": 50,
      "all-on-4-package-both-arches": 13999,
      "all-on-four-system-nobel-straumann": 13500,
      "implant-supported-overdenture-3-implants": 0,
      "3-on-6-dental-implants": 0,
      "zirconium-veneer": 0,
      "metal-brackets-monthly-fees": 0,
      "bone-graft-small": 200,
      "straumann-implant-package": 1800,
      "all-on-six-system-nobel-biocare": 0,
      "complete-removable-denture": 0,
      gingivoplasty: 0,
      "partial-removable-denture": 0,
      "bone-graft-medium": 0,
      "implants-supported-porcelain-bridge-8-implants": 0,
      "snap-on-4-package-both-arches": 10000,
      "crown-over-implant-abutment": 650,
      "ct-scan-3d-xray": 150,
      "extraction-simple": 50,
      "pure-ceramic-implant": 0,
      "implant-supported-overdenture-2-implants": 0,
      gingivectomy: 0,
      "porcelain-fused-to-metal-crown": 0,
      "titanium-dental-implant-crown": 1550,
      "porcelain-fused-to-gold-crown": 0,
      "extraction-surgical-impacted": 180,
      "post-core-build-up": 0,
      "titanium-dental-implant-only": 900,
      "sinus-lift-starting-at": 700,
      "deep-cleaning-scaling-root-planing": 0,
      "zirconium-veneer-gc": 0,
      "temporary-crown-veneer-gc": 30,
      "root-canal-not-including-crown": 300,
    },
  },
  {
    id: 2,
    name: "CEY Dental Boutique",
    location: "Ciudad de México",
    picture: "https://via.placeholder.com/150x100?text=CEY+Dental",
    highlights: ["Aesthetic", "Smile Design"],
    procedurePricing: {
      "three-unit-bridge": 600,
      "composite-filling": 74,
    },
  },
  {
    id: 3,
    name: "Biodental Care",
    location: "Tijuana, Mexico",
    picture: "https://via.placeholder.com/150x100?text=Biodental+Care",
    highlights: ["Holistic", "Biocompatible", "Implants"],
    procedurePricing: {
      "all-on-four": 9500,
      "all-on-six": 11000,
      "three-unit-bridge": 1440,
      "bone-graft-large": 300,
      "composite-filling": 70,
    },
  },
  {
    id: 4,
    name: "New Age Dental",
    location: "Tijuana, Mexico",
    picture: "https://via.placeholder.com/150x100?text=New+Age+Dental",
    highlights: ["State-of-the-Art", "Cosmetic", "Full Mouth Rehab"],
    procedurePricing: {
      "all-on-four": 10649,
      "all-on-six": 12629,
      "three-unit-bridge": 1500,
      "bone-graft-large": 550,
      "composite-filling": 150,
    },
  },
  {
    id: 5,
    name: "Clinica Dental Laser Cd. Juarez",
    location: "Ciudad Juarez, Mexico",
    picture: "https://via.placeholder.com/150x100?text=Dental+Laser",
    highlights: ["Laser Assisted", "Implantology"],
    procedurePricing: {
      "all-on-four": 11000,
      "all-on-six": 14700,
    },
  },
];

export const treatments = [
  { id: "all-on-four", name: "All on Four", maxUnits: 1 },
  { id: "all-on-six", name: "All on Six", maxUnits: 1 },
  { id: "three-unit-bridge", name: "3 Unit Bridge", maxUnits: 4 },
  { id: "bone-graft-large", name: "Bone Graft (Large)", maxUnits: 2 },
  { id: "composite-filling", name: "Composite Filling", maxUnits: 10 },
  { id: "zirconium-crown", name: "Zirconium Crown", maxUnits: 4 },
  { id: "snap-on-4", name: "Snap On 4", maxUnits: 1 },
  { id: "titanium-implant", name: "Titanium Implant", maxUnits: 4 },
  { id: "porcelain-veneer", name: "Porcelain Veneer", maxUnits: 8 },
  { id: "sinus-lift", name: "Sinus Lift", maxUnits: 2 },
  { id: "root-canal", name: "Root Canal", maxUnits: 8 },
  { id: "temporary-crown", name: "Temporary Crown", maxUnits: 4 },
  { id: "iv-sedation", name: "IV Sedation", maxUnits: 1 },
  { id: "dental-cleaning", name: "Dental Cleaning", maxUnits: 1 },
  {
    id: "all-on-4-package-both-arches",
    name: "All on 4 Package (Both Arches)",
    maxUnits: 1,
  },
  {
    id: "all-on-four-system-nobel-straumann",
    name: "All on Four System (Nobel Straumann)",
    maxUnits: 1,
  },
  {
    id: "implant-supported-overdenture-3-implants",
    name: "Implant Supported Overdenture (3 Implants)",
    maxUnits: 1,
  },
  { id: "3-on-6-dental-implants", name: "3 on 6 Dental Implants", maxUnits: 1 },
  { id: "zirconium-veneer", name: "Zirconium Veneer", maxUnits: 8 },
  {
    id: "metal-brackets-monthly-fees",
    name: "Metal Brackets (Monthly Fees)",
    maxUnits: 12,
  },
  { id: "bone-graft-small", name: "Bone Graft (Small)", maxUnits: 2 },
  {
    id: "straumann-implant-package",
    name: "Straumann Implant Package",
    maxUnits: 1,
  },
  {
    id: "all-on-six-system-nobel-biocare",
    name: "All on Six System (Nobel Biocare)",
    maxUnits: 1,
  },
  {
    id: "complete-removable-denture",
    name: "Complete Removable Denture",
    maxUnits: 1,
  },
  { id: "gingivoplasty", name: "Gingivoplasty", maxUnits: 1 },
  {
    id: "partial-removable-denture",
    name: "Partial Removable Denture",
    maxUnits: 1,
  },
  { id: "bone-graft-medium", name: "Bone Graft (Medium)", maxUnits: 2 },
  {
    id: "implants-supported-porcelain-bridge-8-implants",
    name: "Implants Supported Porcelain Bridge (8 Implants)",
    maxUnits: 1,
  },
  {
    id: "snap-on-4-package-both-arches",
    name: "Snap On 4 Package (Both Arches)",
    maxUnits: 1,
  },
  {
    id: "crown-over-implant-abutment",
    name: "Crown Over Implant Abutment",
    maxUnits: 4,
  },
  { id: "ct-scan-3d-xray", name: "CT Scan 3D X-Ray", maxUnits: 1 },
  { id: "extraction-simple", name: "Extraction (Simple)", maxUnits: 4 },
  { id: "pure-ceramic-implant", name: "Pure Ceramic Implant", maxUnits: 4 },
  {
    id: "implant-supported-overdenture-2-implants",
    name: "Implant Supported Overdenture (2 Implants)",
    maxUnits: 1,
  },
  { id: "gingivectomy", name: "Gingivectomy", maxUnits: 1 },
  {
    id: "porcelain-fused-to-metal-crown",
    name: "Porcelain Fused to Metal Crown",
    maxUnits: 4,
  },
  {
    id: "titanium-dental-implant-crown",
    name: "Titanium Dental Implant Crown",
    maxUnits: 4,
  },
  {
    id: "porcelain-fused-to-gold-crown",
    name: "Porcelain Fused to Gold Crown",
    maxUnits: 4,
  },
  {
    id: "extraction-surgical-impacted",
    name: "Extraction (Surgical Impacted)",
    maxUnits: 4,
  },
  { id: "post-core-build-up", name: "Post Core Build Up", maxUnits: 4 },
  {
    id: "titanium-dental-implant-only",
    name: "Titanium Dental Implant Only",
    maxUnits: 4,
  },
  {
    id: "sinus-lift-starting-at",
    name: "Sinus Lift (Starting At)",
    maxUnits: 2,
  },
  {
    id: "deep-cleaning-scaling-root-planing",
    name: "Deep Cleaning / Scaling & Root Planing",
    maxUnits: 4,
  },
  { id: "zirconium-veneer-gc", name: "Zirconium Veneer (GC)", maxUnits: 8 },
  {
    id: "temporary-crown-veneer-gc",
    name: "Temporary Crown Veneer (GC)",
    maxUnits: 4,
  },
  {
    id: "root-canal-not-including-crown",
    name: "Root Canal (Not Including Crown)",
    maxUnits: 8,
  },
];
